name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install bundler
      run: |
        gem install bundler:2.2.27
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Create google-service.json
      run: cat /home/runner/work/AkuButuhBakso/AkuButuhBakso/app/google-services.json | base64

    - name: Putting data into google-service.json
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/AkuButuhBakso/AkuButuhBakso/app/google-services.json

    - name: Create google-service.json
      run: cat /home/runner/work/AkuButuhBakso/AkuButuhBakso/fastlane/gservice_creds.json | base64

    - name: Putting data into google-service.json
      env:
        DATA: ${{ secrets.GOOGLE_CREDS_JSON }}
      run: echo $DATA > /home/runner/work/AkuButuhBakso/AkuButuhBakso/fastlane/gservice_creds.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

#    - name: Build with Gradle
#      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Build & deploy Android release
      run: bundle exec fastlane submitToFirebaseDistribution
